[server]

bind = ""
read_timeout = ""
write_timeout = ""
download_timeout = ""
concurrency = ""
max_clients = ""
ttl = ""

[security]

allow_origins = ""
max_src_dimension = ""
max_src_resolution = ""

[compression]

gzip_compression = ""

[misc]

server_url = ""
cache_root = ""
cache_size = ""
